### ISSUE TITLE
Display error

### ISSUE THREAD

**Issue by ghost** [juraj-hrivnak/SimpleDifficulty#6]
![image](https://github.com/juraj-hrivnak/SimpleDifficulty/assets/83486178/db5cfaf6-8d5b-4c07-8ced-119f1f9088be)
![image](https://github.com/juraj-hrivnak/SimpleDifficulty/assets/83486178/5f7d4c54-c5b1-430e-8775-bca7bdfcba18)
This happens when simpledifficulty, betterpvp, and classicbar are loaded together.

**Comment by juraj-hrivnak** [comment]
Duplicate of #2
